// Compact, expandable tool content. Highlight only known languages; logs and
// prose must not be auto-detected as code. All fallback paths escape HTML.
import { escHtml, parseToolArgs } from "./render.js";

export const TOOL_PREVIEW_LINES = 8;
const MAX_HIGHLIGHT_CHARS = 100_000;

const FILE_LANGUAGES = {
  js: "javascript", jsx: "javascript", mjs: "javascript", cjs: "javascript",
  ts: "typescript", tsx: "typescript", mts: "typescript", cts: "typescript",
  py: "python", rb: "ruby", rs: "rust", go: "go", java: "java",
  c: "c", h: "c", cc: "cpp", cpp: "cpp", hpp: "cpp", cs: "csharp",
  sh: "bash", bash: "bash", zsh: "bash", fish: "shell",
  json: "json", jsonl: "json", yaml: "yaml", yml: "yaml",
  toml: "ini", ini: "ini", css: "css", scss: "scss",
  html: "xml", htm: "xml", xml: "xml", svg: "xml",
  md: "markdown", mdx: "markdown", sql: "sql", diff: "diff", patch: "diff",
};

export function toolLanguageFromPath(path) {
  if (typeof path !== "string") return "";
  const basename = path.split(/[\\/]/).pop().toLowerCase();
  if (basename === "dockerfile") return "dockerfile";
  if (basename === "makefile") return "makefile";
  return FILE_LANGUAGES[basename.split(".").pop()] || "";
}

export function toolResultLanguage(toolName, args, content, isError) {
  if (isError) return "";
  if ((toolName || "").toLowerCase() === "read") {
    const parsed = parseToolArgs(args);
    const language = toolLanguageFromPath(parsed?.path || parsed?.file_path);
    if (language) return language;
  }
  // Structured output from any tool can be highlighted without guessing a
  // language. Preserve its original formatting and never parse huge logs.
  if (content.length <= MAX_HIGHLIGHT_CHARS && /^\s*[{[]/.test(content)) {
    try { JSON.parse(content); return "json"; } catch { /* ordinary output */ }
  }
  return "";
}

export function highlightToolCode(text, language) {
  const hljs = globalThis.hljs;
  if (language && text.length <= MAX_HIGHLIGHT_CHARS && hljs?.getLanguage(language)) {
    try {
      return hljs.highlight(text, { language, ignoreIllegals: true }).value;
    } catch { /* keep tool output readable if highlighting fails */ }
  }
  return escHtml(text);
}

/** Rich lines are trusted HTML generated by our diff/checklist renderers,
 * never tool-supplied HTML. Slice before highlighting/rendering so collapsed
 * outputs keep the DOM small without throwing away the original content. */
export function renderToolBody({ body, bodyLines, language = "", key, expanded, label }) {
  if (!body && !bodyLines?.length) return "";
  const lines = bodyLines || body.replace(/\r\n/g, "\n").split("\n");
  const hasMore = lines.length > TOOL_PREVIEW_LINES;
  const isExpanded = expanded.has(key);
  const visible = hasMore && !isExpanded ? lines.slice(0, TOOL_PREVIEW_LINES) : lines;
  const id = `tool-body:${key}`;
  const content = bodyLines
    ? `<div class="tool-rich-lines">${visible.join("")}</div>`
    : `<pre class="tool-code"><code${language ? ` class="hljs language-${escHtml(language)}"` : ""}>${highlightToolCode(visible.join("\n"), language)}</code></pre>`;
  const toggle = hasMore
    ? `<button type="button" class="tool-expand" data-toggle="${escHtml(key)}" aria-expanded="${isExpanded}" aria-controls="${escHtml(id)}" aria-label="${isExpanded ? "Collapse" : "Expand"} ${escHtml(label)}">${isExpanded ? "Show less" : `Show all ${lines.length} lines`} <span aria-hidden="true">${isExpanded ? "▴" : "▾"}</span></button>`
    : "";
  return `<div class="tool-content"><div class="tool-content-label">${escHtml(label)}</div><div id="${escHtml(id)}" class="tool-body">${content}</div>${toggle}</div>`;
}
